ARG VERSION=latest
FROM alpine:${VERSION} AS build

# add testing repository
RUN echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# update apk repositories
RUN apk update

# upgrade all
RUN apk upgrade

# add c build tools
RUN apk add build-base

# add git
RUN apk add git

# add php dev
RUN apk add php82-dev@testing

# add zlib dev
RUN apk add zlib-dev@testing

# clone php-spx
RUN git clone https://github.com/NoiseByNorthwest/php-spx.git

# set workdir
WORKDIR /php-spx

# checkout release (php 8.2 needs master)
#RUN git checkout tags/v0.4.12

# fix ./configure "Cannot find php-config. Please use --with-php-config=PATH"
RUN ln -s /usr/bin/php-config82 /usr/bin/php-config

# build php-spx
RUN phpize82
RUN ./configure
RUN make

# start again with a new image
FROM scratch

# get version
ARG VERSION

# copy spx module from alpine image to the scratch image so files can be copied back to host
COPY --from=build /php-spx/modules/spx.so alpine-$VERSION/spx.so
